### ISSUE TITLE
`localeIndexOf` does not work on multiple-char letters

### ISSUE THREAD

**Issue by ilonatommy** [arty-name/locale-index-of#27]
In some locales, e.g. `sk-SK` there are letters that consist of more than one sign: `ch` is one letter in Slovak and calling:
```
const shouldNotFindAnything = localeIndexOf('ch', 'h', 'sk-SK');
```
should return -1. If we use e.g. 
```
"ch".localeCompare("h", "sk-SK");
```
we are getting "1" that shows that collation in `localeCompare` works fine (for `en` it's comparing first "c" with "h" and returns -1.
Another test case that you can use to fix the problem is:
```
const shouldBeSeven = localeIndexOf('chodit hore', 'ho', 'sk-SK');
```
The first `h` on position 1 should be ignored as it is a part of `ch`. Expected result: 7. Current result: 1.

The reason for it is faulty `Intl.Segmenter`. It is not able to correctly segment characters in a locale. In the fix we would need to either make an issue on the segmenter and fix it or use some other, workaround function.
```
const segmenterSk = new Intl.Segmenter('sk-SK', { granularity: 'grapheme' });
Array.from(segmenterSk.segment("chh"));
// (3) [{…}, {…}, {…}]
// 0 :  {segment: 'c', index: 0, input: 'chh'}
// 1 :  {segment: 'h', index: 1, input: 'chh'}
// 2 :  {segment: 'h', index: 2, input: 'chh'}
// length :  3 [[Prototype]] :  Array(0)
```

**Comment by arty-name** [comment]
Thank you for the well-researched report!

I feel more out of my depth with every report I receive. I am not really confident about the conclusions I am making here. 

I started Chrome in Slovak language and opened [a page in Slovak language containing words "chodiť hore"](https://slovnik.aktuality.sk/preklad/slovensko-nemecky/?q=chodi%C5%A5+hore-dolu). Then I used in-page search for the letter "h" and it was highlighted inside of "ch" as well. The `localeIndexOf` use-case is exactly like in-page search, so it matches the browser behavior here.

The `localeCompare` has options, and one of those is `usage` which can be `sort` or `search`. The `localeIndexOf` is much closer to search than to sort. The value of `usage` is significant in this case:

```js
"ch".localeCompare("h", "sk-SK", { usage: 'sort' }); // 1
"ch".localeCompare("h", "sk-SK", { usage: 'search' }); // -1
```

I don’t see an alternative to using `Intl.Segmenter` here. It’s choice of granularity is limited unfortunately: there’s only `grapheme` smaller than `word`. Looking at the [Wikipedia article for grapheme](https://en.wikipedia.org/wiki/Grapheme) I see the following: 

> Some linguists consider [digraphs](https://en.wikipedia.org/wiki/Digraph_(orthography)) like the ⟨sh⟩ in ship to be distinct graphemes, but these are generally analyzed as sequences of graphemes.

The issue does not seem very clear-cut to me. Might be that the behavior you expect from the software is not what other developers and even linguists agree on. This happened to me more than once. In any case, feel free to report the behavior of the segmenter to the browsers. They might rely on the ICU library for this heavy lifting, so this is another thing worth researching. 

Sorry that I can’t help beyond that.
